### ISSUE TITLE
Is it running on linux?

### ISSUE THREAD

**Issue by papiche** [Aerion/uptobox-dl#2]

**Comment by Aerion** [comment]
Hi,

It may be run everywhere (I use it on Linux), as long as you have .NET Runtime 3.1 installed, or if you build it with the `--self-contained true` argument.

I have updated the [README.md](https://github.com/Aerion/uptobox-dl#run-from-release-artifacts) file with more details as to how to run this software.

If some steps are not clear, please tell me so that I can improve that section!

**Comment by Aerion** [comment]
Hi @SalimF, thanks for the report.

With [https://github.com/Aerion/uptobox-dl/releases/tag/v1.1.1](v1.1.1), I updated the build so that it targets netcoreapp3.1, net5.0, net6.0.

I tested this artifact on runtime `Microsoft.NETCore.App 6.0.5` on Archlinux and it works.

Let me know if you face any issues.

**Comment by SalimF** [comment]
> updated the build so that it targets netcoreapp3.1, net5.0, net6.0.

Yeah, thanks works perfectly 

```
./uptobox-dl' 
uptobox-dl 1.1.1
Copyright (C) 2022 uptobox-dl
```
