### ISSUE TITLE
Don't run on windows

### ISSUE THREAD

**Issue by Valentin-Bleuse** [Aerion/uptobox-dl#7]
When I click on the .exe file, it does nothing... I'm lost

**Comment by Aerion** [comment]
Hi, this is a program that takes its arguments from the command line.
For instance, could you try following the method 2 of this tutorial? https://www.wikihow.com/Run-a-Program-on-Command-Prompt

If, instead of `file.exe` in the wikihow article, you replace it with `uptobox-dl.exe --help`, you'll see the help message for this program.

**Comment by Valentin-Bleuse** [comment]
I have tried this, it opens a new cmd's window which is closed few seconds after being launched.

**Comment by Aerion** [comment]
I tested on windows recently and the program works.
Please follow the instructions in the above wikihow, and make sure that you have .NET runtime installed.

Steps to follow on Windows:
* Download the latest version (e.g. for 1.2.1): https://github.com/Aerion/uptobox-dl/releases/download/v1.2.1/uptobox-dl-v1.2.1-win-x64.zip
* Extract the zip in a folder (say `C:\Users\foo\Downloads`)
* Open a cmd or powershell windows
* Either:
  * Drag and drop the `uptobox-dl.exe` file in the window
  * Type `C:\Users\foo\Downloads\uptobox-dl.exe`
* Press Enter

Then, the help message should be displayed, with the uptobox version.
